apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: college-app

  template:
    metadata:
      labels:
        app: college-app

    spec:
      containers:
        - name: college-app
          image: renukachavan/college-app:v4

          ports:
            - containerPort: 8090

          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb-0.mongodb:27017,mongodb-1.mongodb:27017,mongodb-2.mongodb:27017/college?replicaSet=rs0"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 45
            periodSeconds: 15
