apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-frontend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: college-frontend

  template:
    metadata:
      labels:
        app: college-frontend

    spec:
      containers:
        - name: college-frontend
          image: renukachavan/college-frontend:v2

          ports:
            - containerPort: 80
