server.port=8090

spring.data.mongodb.uri=mongodb://mongodb-0.mongodb,mongodb-1.mongodb,mongodb-2.mongodb/college?replicaSet=rs0

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

